### ISSUE TITLE
generate Pypi/conda packages

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#23]
Good example would be the MRD repo, see https://github.com/microsoft/yardl/issues/108#issuecomment-2135292040 for some info.

It looks like for MRD, the generated code is added to the repo, presumably via some actions etc. Usually I don't like adding generated code to a repo, but otherwise we probably need 2 different repos (the model, and the generated code). Suggestions welcome!

**Comment by lukepolson** [comment]
@KrisThielemans it seems like they have a the following actions
1. Create the environment necessary for using `yardl`: https://github.com/ismrmrd/mrd/blob/main/.github/actions/configure-mrd-build-environment/action.yml
2. Build the source code for cpp/python/matlab using yardl https://github.com/ismrmrd/mrd/blob/main/.github/workflows/mrd_build.yml
3. Then some code for (a) publishing to pypi https://github.com/ismrmrd/mrd/blob/main/.github/workflows/mrd_pypi.yml and (b) publishing to conda https://github.com/ismrmrd/mrd/blob/main/.github/workflows/mrd_conda.yml

I'll play around with a forked version of the repository and test-pypi to see if I can get something similar to what they have.

**Comment by lukepolson** [comment]
@KrisThielemans here are my initial thoughts: let me know if you think there's an issue with this though:

1. We add a `pyproject.toml` file to the `/python`  directory which acts as the requirements file for all code generated by running `yardl`. e.g., after `yardl` has been ran, there will be a `/prd`  folder with a correpsonding `pyproject.toml` file inside the `python` folder.
2. We build the code inside the python directory using `python -m build`, which will read the `pyproject.toml` file and create a build version of the `/prd` file. Then we publish to pypi
3. When users download this, they'll *only* have access to the code that was generated in the `/prd` folder. Which I suspect is what they want. Then they can, for example, run `pip install prdpy` and then `from prdpy.binary import BinaryPrdExperimentWriter` and etc...
