### ISSUE TITLE
pyright error on `subject`

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#31]
```
$ pyright  *py
  /home/sirfuser/devel/PRDdefinition/python/prd_analysis.py:14:42 - error: "subject" is not a known attribute of "None" (reportOptionalMemberAccess)
```
No idea why this is. yardl bug?
@johnstairs

**Comment by johnstairs** [comment]
The issue is that the `exam` field on `Header` is optional, so the value of `exam` is either `Header` or `None`, and that the expression could fail  because `None` has no `subject` attribute.
