### ISSUE TITLE
vscode-dev-containers out-of-date

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#45]
https://github.com/microsoft/vscode-dev-containers/ is archived, but we are using it in our devcontainer.

@johnstairs @naegelejd can you help, please?

**Comment by johnstairs** [comment]
I'll update it

**Comment by KrisThielemans** [comment]
could push to #44

**Comment by KrisThielemans** [comment]
Those updates will apply for https://github.com/ETSInitiative/PETSIRDUseCaseTemplate/issues/8 as well. If you could give that a go as well, you'll get free attendance to the hackathon 😄
