### ISSUE TITLE
symmetry of module_pair_sgidlut

### ISSUE THREAD

**Issue by gschramm** [ETSInitiative/PETSIRD#52]
If I understand correctly, the `module_pair_sgidlut` matrix should be symmetric.

In the current python petsird generator example, it is not (but almost)
```
In [13]: module_pair_SGID_LUT[0,39]
Out[13]: 74

In [14]: module_pair_SGID_LUT[39,0]
Out[14]: 73
``` 

https://github.com/ETSInitiative/PETSIRD/blob/ae3a0484a128f805a2143cc0d010d01557cf902f/python/petsird_generator.py#L168

**Comment by KrisThielemans** [comment]
we concluded it is not symmetry (i.e. needs additional reordering)

**Comment by gschramm** [comment]
One related thought that I had on my flight back home: 
Should we stimualted people to treat the SGID LUT as an upper triangle matrix?

That could potentially avoid confusion, but obviously might need some sorting of the detector order in every LM event.
